import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="bg-white shadow-md sticky top-0 z-50">
        <nav className="container mx-auto flex items-center justify-between py-4 px-6">
          <div className="text-2xl font-bold text-gray-900 tracking-tight">
            <Link href="/">MyApp</Link>
          </div>
          <ul className="flex space-x-6 text-base font-medium">
            <li>
              <Link href="/" className="hover:text-blue-600 transition-colors">Home</Link>
            </li>   
            <li>
              <Link href="/blog" className="hover:text-blue-600 transition-colors">Blog</Link>
            </li>
            <li>
              <Link href="/contact" className="hover:text-blue-600 transition-colors">Contact</Link>
            </li>
            <li>
              <Link href="/products" className="hover:text-blue-600 transition-colors">Products</Link>
            </li>
            <li>
              <Link href="/login" className="hover:text-blue-600 transition-colors">Login</Link>
            </li>
          </ul>
        </nav>
      </header>
      <main>
         {children}
      </main>
        <footer>

      </footer>
      </body>
      
    </html>
  );
}
